steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=us.gcr.io/$PROJECT_ID/$_IMAGE
  - --cache=true
  - --cache-ttl=24h
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'flux-web', '--image', 'us.gcr.io/$PROJECT_ID/$_IMAGE', '--region', 'us-central1','--platform', 'managed', '--quiet']
substitutions:
  _IMAGE: flux-web
