version: "3"

services:
  app:
    build: .
    container_name: flux-web
    expose:
      - 3000
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:flux.crossman.page"
      - "traefik.port=3000"

networks:
  traefik:
    external:
      name: traefik
