version: "3.5"

services:
  flux:
    build: .
    container_name: flux
    expose:
      - 3000
    networks:
      - web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:fluxfinancial.net"
      - "traefik.port=3000"
  
  proxy:
    image: traefik:latest
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    restart: always

networks:
  web:
    external:
      name: web
